name: Github Action to trigger downstream job
on:
  issue_comment:
    types: [created, edited]

jobs:
  trigger_workflow:
    uses: raukadah/ci-playground/.github/workflows/github-action-trigger-downstream-job-reusable-workflow.yaml@main
